# Generated by Django 4.0.5 on 2022-07-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_distributor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
    ]
